name = "Crystallographic"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Crystallographic"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[lean_lib]]
name = "Crystallographic"
