name = "Crystallographic"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Crystallographic"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"

[[require]]
name = "Dress"
git = "https://github.com/e-vergo/Dress"
rev = "main"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "v4.27.0-rc1"

[[lean_lib]]
name = "Crystallographic"
