name = "Crystallographic"
defaultTargets = ["Crystallographic"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.27.0"

[[require]]
name = "Dress"
git = "https://github.com/e-vergo/Dress.git"
rev = "main"

[[require]]
name = "verso"
git = "https://github.com/e-vergo/verso.git"
rev = "main"

[[require]]
scope = "dev"
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4.git"
rev = "01e1433"  # v4.27.0 compatible

[[lean_lib]]
name = "Crystallographic"

[[lean_exe]]
name = "generate-paper-verso"
root = "GeneratePaper"
