title: Crystallographic Restriction Theorem
description: Formal verification of the crystallographic restriction theorem in Lean 4
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag

# GitHub repository info
repository: e-vergo/General_Crystallographic_Restriction

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
